### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ayaz-ashrapov** [rafmio/Ethereum#5]

**Comment by ayaz-ashrapov** [comment]
Write at least 2 unit tests and send them to me for review

**Comment by ayaz-ashrapov** [comment]
Read about unit tests, mocks and how to use mocks in Go

**Comment by rafmio** [comment]
> Write at least 2 unit tests and send them to me for review
Done
https://github.com/rafmio/Ethereum/blob/delete-data/src/generateAcc_test.go
https://github.com/rafmio/Ethereum/blob/delete-data/src/connectDB_test.go

**Comment by rafmio** [comment]
> first unit test should be about creating account

https://github.com/rafmio/Ethereum/blob/delete-data/src/generateAcc_test.go
